In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tushare as ts

使用tushare包获取某股票的历史行情数据

In [5]:
df = ts.get_k_data("600519", start='1988-01-01')
df.to_csv("600519.csv")

输出该股票所有收盘比开盘上涨3%以上的日期

In [15]:
df = pd.read_csv("600519.csv", parse_dates=['date'], index_col='date')[['open','close','high','low']]
df[(df['close']-df['open'])/df['open'] >= 0.03]

DatetimeIndex(['2001-08-27', '2001-08-28', '2001-09-10', '2001-12-21',
               '2002-01-18', '2002-01-31', '2003-01-14', '2003-10-29',
               '2004-01-05', '2004-01-13',
               ...
               '2017-01-04', '2017-02-20', '2017-04-25', '2017-08-14',
               '2017-10-19', '2017-10-27', '2017-11-10', '2017-11-16',
               '2017-11-28', '2017-12-11'],
              dtype='datetime64[ns]', name='date', length=275, freq=None)

输出该股票所有开盘比前日收盘跌幅超过2%的日期

In [19]:
df = df['2010':]
money = 0

               open    close     high      low
date
2010-01-04  111.319  109.986  111.319  109.578
2010-01-05  110.665  109.662  110.995  109.377
2010-01-06  109.371  107.928  109.701  107.636
2010-01-07  107.928  105.960  108.206  104.769
2010-01-08  106.141  104.847  106.141  103.617
2010-01-11  105.882  104.387  106.724  103.876
2010-01-12  104.491  107.209  107.546  103.947
2010-01-13  106.135  104.484  106.886  104.200
2010-01-14  104.847  109.080  109.507  104.847
2010-01-15  109.060  109.940  112.212  109.060
2010-01-18  110.025  110.659  111.487  109.960
2010-01-19  110.665  109.876  110.995  109.701
2010-01-20  109.966  107.384  110.122  107.306
2010-01-21  107.345  107.908  108.976  107.112
2010-01-22  107.824  106.225  108.271  104.776
2010-01-25  106.044  107.462  108.277  105.177
2010-01-26  108.905  107.889  110.135  106.530
2010-01-27  107.455  106.128  108.588  105.882
2010-01-28  106.051  109.507  110.251  105.818
2010-01-29  109.992  109.080  110.154  108.523
2010-02-01  109.300  109.306  109.753  108.089
2010-02-02  108.730  107.772  110.025  107.623
2010-02-03  107.572  107.390  108.795  106.271
2010-02-04  107.371  109.118  109.539  106.873
2010-02-05  108.478  110.834  111.241  108.083
2010-02-08  110.834  110.821  113.649  110.361
2010-02-09  111.319  110.743  112.180  110.368
2010-02-10  111.319  111.209  111.701  110.478
2010-02-11  111.189  112.212  112.898  111.060
2010-02-12  112.594  112.024  112.743  111.448
...             ...      ...      ...      ...
2017-11-06  641.500  653.060  657.620  640.200
2017-11-07  650.580  642.070  657.150  638.180
2017-11-08  642.330  650.380  654.500  642.330
2017-11-09  648.000  650.070  654.150  644.610
2017-11-10  650.430  677.950  683.400  650.430
2017-11-13  680.000  687.880  692.780  675.800
2017-11-14  687.140  678.750  687.220  677.350
2017-11-15  678.750  688.080  689.990  674.000
2017-11-16  686.010  719.110  719.960  686.010
2017-11-17  696.000  690.250  709.000  677.770
2017-11-20  676.800  679.150  685.600  660.000
2017-11-21  669.000  677.250  688.800  662.020
2017-11-22  677.000  650.520  688.000  650.000
2017-11-23  642.000  633.730  646.000  630.220
2017-11-24  635.900  630.040  642.500  622.230
2017-11-27  634.000  621.290  636.330  613.010
2017-11-28  625.060  648.230  648.880  624.000
2017-11-29  649.940  638.120  651.970  634.010
2017-11-30  635.510  631.000  648.480  626.000
2017-12-01  638.010  622.350  638.990  620.130
2017-12-04  623.950  637.790  644.100  616.720
2017-12-05  634.000  632.960  647.400  630.130
2017-12-06  631.500  625.010  644.100  620.000
2017-12-07  624.950  616.690  624.990  615.260
2017-12-08  615.420  627.280  628.850  615.420
2017-12-11  631.000  650.990  651.950  631.000
2017-12-12  658.700  651.320  658.770  651.020
2017-12-13  654.990  668.210  670.000  650.720
2017-12-14  669.980  664.550  671.300  660.500
2017-12-15  664.000  653.790  667.950  650.780

[1928 rows x 4 columns]